services:
  redis:
    image: redis:latest
    container_name: stroll-proj-cache
    tty: true
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  db:
    image: postgres:14
    container_name: stroll-db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-seed:
    image: postgres:14
    depends_on:
      - db
    environment:
      PGPASSWORD: ${PG_PASS}
    volumes:
      - ./docker/postgresql/sqls:/sqls
    command: psql -h db -U ${PG_USER} -d ${PG_DB} -f /sqls/seed_data.sql -q -t
    profiles:
      - extra

volumes:
  redis-data: